apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-users

resources:
  - ../../base
  - configmaps.yaml
  - ingress.yaml
  - middlewares.yaml
  - pod-monitor.yaml
  - secrets.yaml

labels:
  - pairs:
      app: web
      version: v1
      platform: sweetrpg
      package: users
      component: web

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: users-web
    newName: ghcr.io/sweetrpg/users-web
    newTag: latest
