---
kind: Service
apiVersion: v1

metadata:
  name: web-v1

spec:
    selector:
        app.kubernetes.io/name: users-web
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: users
    type: ClusterIP
    ports:
        - name: http
          port: 8080
          targetPort: http
