---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: web-v1
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: sweetrpg-users-errors-shared-web@kubernetescrd,sweetrpg-users-strip-prefix-web@kubernetescrd
    kubernetes.io/ingress.class: traefik

spec:
  ingressClassName: traefik
  rules:
    - host: sweetrpg.local
      http:
        paths:
          - pathType: Prefix
            path: /users
            backend:
              service:
                name: web-v1
                port:
                  name: http
